- name: Create JCasC directory
  file:
    path: /var/lib/jenkins/casc_configs
    state: directory
    owner: jenkins
    group: jenkins

- name: Copy JCasC config
  template:
    src: templates/jenkins.yaml.j2
    dest: /var/lib/jenkins/casc_configs/jenkins.yaml
    owner: jenkins
    group: jenkins

- name: Create systemd override directory
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory

- name: Set JCasC via systemd override
  copy:
    dest: /etc/systemd/system/jenkins.service.d/casc.conf
    content: |
      [Service]
      Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/casc_configs"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Ensure Jenkins directories are owned by the jenkins user
  ansible.builtin.file:
    path: "{{ item }}"
    owner: jenkins
    group: jenkins
    recurse: yes
    state: directory
  become: true
  loop:
    - /var/lib/jenkins
    - /var/cache/jenkins
   # - /var/log/jenkins  

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted