apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-root-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: ClusterSecretStore
  target:
    name: mongodb-root-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: mongodb-credentials
        property: username
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: mongodb-credentials
        property: password