jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false


  clouds:
  - kubernetes:
      name: kubernetes
      serverUrl: https://B8F7C26435E83EBA66E9A8B39711DD8A.gr7.us-east-1.eks.amazonaws.com
      namespace: jenkins
      jenkinsUrl: http://35.172.209.221:8080
      containerCapStr: "10"
      templates:
          - name: "jenkins-agent"
            label: "jenkins-agent"
            serviceAccount: "jenkins"

            containers:

              - name: jnlp
                image: jenkins/inbound-agent
                ttyEnabled: true

              - name: kaniko
                image: gcr.io/kaniko-project/executor:latest
                command:
                  - cat
                ttyEnabled: true

              - name: trivy
                image: aquasec/trivy
                command:
                  - cat
                ttyEnabled: true

              - name: owasp
                image: owasp/dependency-check
                command:
                  - cat
                ttyEnabled: true



  # unclassified:
  # sonarGlobalConfiguration:
  #   installations:
  #     - name: sonarqube
  #       serverUrl: http://sonarqube.sonarqube.svc.cluster.local
  #       credentialsId: sonar-token

  # credentials:
  #   system:
  #     domainCredentials:
  #       - credentials:
  #         - aws:
  #             id: aws-credentials
  #             accessKey: AWS_ACCESS_KEY
  #             secretKey: AWS_SECRET_KEY
  
 