apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodejs-app-mongo-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-store   
    kind: ClusterSecretStore          
  target:
    name: nodejs-app-secret           # K8s Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: mongodb-credentials      
        property: MONGO_URI           