apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nodejs-deployment.yaml
- nodejs-service.yaml
- configmap.yaml
images:
- name: 054892330771.dkr.ecr.us-east-1.amazonaws.com/myapp
  newTag: 8.0.0
