apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Nayra000/Production-Grade-DevSecOps.git
    targetRevision:  main
    path: k8s-manifests/secrets

  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true