apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: "10.0.0"

    helm:
      values: |
        service:
          type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: alb

          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/healthcheck-path: /api/system/status
            alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
            alb.ingress.kubernetes.io/group.name: platform-alb   

          hosts:
            - name: ""
              path: /sonarqube
              pathType: Prefix

        persistence:
          enabled: false

        sonarWebContext: /sonarqube/

        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi

        postgresql:
          enabled: true

          image:
            registry: docker.io
            repository: bitnamilegacy/postgresql
            tag: 16.3.0

          auth:
            username: sonar
            database: sonarqube
            existingSecret: sonarqube-postgres-credentials

        startupProbe:
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 30
          sonarWebContext: /sonarqube/

        readinessProbe:
          initialDelaySeconds: 60
          sonarWebContext: /sonarqube/


        livenessProbe:
          initialDelaySeconds: 60
          sonarWebContext: /sonarqube/


  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true