service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /sonarqube/api/system/status
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    alb.ingress.kubernetes.io/group.name: platform-alb

  hosts:
    - name: ""
      path: /sonarqube
      pathType: Prefix
      backend:
        service:
          name: sonarqube
          port:
            number: 9000



env:
  SONAR_WEB_CONTEXT: /sonarqube

persistence:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

postgresql:
  enabled: true

  auth:
    username: sonar
    password: sonar
    database: sonarqube

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: sha256:a8f7e1bb6fe69f43d82634cb5561e78054a5cba92613d056e9278482dc4bc700

startupProbe:
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 30    
  timeoutSeconds: 10